### ISSUE TITLE
宝塔搭建本项目，有点问题，希望作者协助一下

### ISSUE THREAD

**Issue by Asheblog** [alishtory/xsadmin_deploy#6]
很不容易把作者写死的data环境大部分改成了www 环境（不要问我为什么我centos6.9装one'sin都是出错的）。

结果现在访问我的页面css全是丢失的，功能大部分都正常了，还待测试，目前日志提示如下错误

请问作者这个默认的网页根目录在哪个文件改》？log没提示。。谢谢作者。

*** Starting uWSGI 2.0.14 (64bit) on [Mon Jul 31 21:33:10 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 31 July 2017 20:11:47
os: Linux-2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016
nodename: FY-201608032152
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /www/xsadmin_deploy/xsadmin
detected binary path: /www/xsadmin_deploy/env/bin/uwsgi
chdir() to /www/xsadmin_deploy/xsadmin
your processes number limit is 5915
your memory page size is 4096 bytes
detected max file descriptor number: 96000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/run/xsadmin.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.0 (default, Jul 31 2017, 15:05:54)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /www/xsadmin_deploy/env
Python main interpreter initialized at 0x2823200
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 913792 bytes (892 KB) for 20 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x2823200 pid: 7520 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7520)
spawned uWSGI worker 1 (pid: 7533, cores: 2)
spawned uWSGI worker 2 (pid: 7534, cores: 2)
spawned uWSGI worker 3 (pid: 7536, cores: 2)
spawned uWSGI worker 4 (pid: 7537, cores: 2)
spawned uWSGI worker 5 (pid: 7540, cores: 2)
spawned uWSGI worker 6 (pid: 7541, cores: 2)
spawned uWSGI worker 7 (pid: 7544, cores: 2)
spawned uWSGI worker 8 (pid: 7546, cores: 2)
spawned uWSGI worker 9 (pid: 7548, cores: 2)
spawned uWSGI worker 10 (pid: 7550, cores: 2)
[pid: 7550|app: 0|req: 1/1] 113.71.219.39 () {40 vars in 682 bytes} [Mon Jul 31 21:33:23 2017] GET / => generated 4824 bytes in 605 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
Mon Jul 31 21:33:24 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Mon Jul 31 21:33:24 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7548|app: 0|req: 1/2] 113.71.219.39 () {40 vars in 646 bytes} [Mon Jul 31 21:33:24 2017] GET /static/css/home.css => generated 82 bytes in 539 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Mon Jul 31 21:33:24 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7537|app: 0|req: 1/3] 113.71.219.39 () {40 vars in 670 bytes} [Mon Jul 31 21:33:24 2017] GET /static/images/logo.png => generated 82 bytes in 563 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7546|app: 0|req: 1/4] 113.71.219.39 () {40 vars in 629 bytes} [Mon Jul 31 21:33:24 2017] GET /static/js/home.js => generated 82 bytes in 567 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7546|app: 0|req: 2/5] 113.71.219.39 () {40 vars in 673 bytes} [Mon Jul 31 21:33:25 2017] GET /static/images/favicon.ico => generated 82 bytes in 13 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7550|app: 0|req: 2/6] 113.71.219.39 () {44 vars in 735 bytes} [Mon Jul 31 21:33:38 2017] GET / => generated 4824 bytes in 23 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 1)
[pid: 7548|app: 0|req: 2/7] 113.71.219.39 () {44 vars in 699 bytes} [Mon Jul 31 21:33:38 2017] GET /static/css/home.css => generated 82 bytes in 12 msecs (HTTP/1.1 404) 2 headers in 80 bytes (2 switches on core 1)
[pid: 7550|app: 0|req: 3/8] 113.71.219.39 () {44 vars in 682 bytes} [Mon Jul 31 21:33:38 2017] GET /static/js/home.js => generated 82 bytes in 11 msecs (HTTP/1.1 404) 2 headers in 80 bytes (2 switches on core 0)
[pid: 7550|app: 0|req: 4/9] 113.71.219.39 () {44 vars in 723 bytes} [Mon Jul 31 21:33:38 2017] GET /static/images/logo.png => generated 82 bytes in 10 msecs (HTTP/1.1 404) 2 headers in 80 bytes (2 switches on core 1)
Mon Jul 31 21:33:38 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7541|app: 0|req: 1/10] 113.71.219.39 () {44 vars in 682 bytes} [Mon Jul 31 21:33:38 2017] GET /static/js/home.js => generated 82 bytes in 440 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Mon Jul 31 21:33:39 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7544|app: 0|req: 1/11] 113.71.219.39 () {44 vars in 726 bytes} [Mon Jul 31 21:33:39 2017] GET /static/images/favicon.ico => generated 82 bytes in 494 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7544|app: 0|req: 2/12] 113.71.219.39 () {42 vars in 739 bytes} [Mon Jul 31 21:33:41 2017] GET /register/ => generated 10300 bytes in 70 msecs (HTTP/1.1 200) 4 headers in 256 bytes (2 switches on core 1)
[pid: 7537|app: 0|req: 3/13] 113.71.219.39 () {42 vars in 744 bytes} [Mon Jul 31 21:33:41 2017] GET /static/css/home.css => generated 82 bytes in 21 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7537|app: 0|req: 3/14] 113.71.219.39 () {42 vars in 727 bytes} [Mon Jul 31 21:33:41 2017] GET /static/js/home.js => generated 82 bytes in 19 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7541|app: 0|req: 2/15] 113.71.219.39 () {42 vars in 768 bytes} [Mon Jul 31 21:33:41 2017] GET /static/images/logo.png => generated 82 bytes in 13 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7541|app: 0|req: 3/16] 113.71.219.39 () {50 vars in 986 bytes} [Mon Jul 31 21:33:42 2017] POST /get_gee_captcha/?t=1501507840527 => generated 105 bytes in 198 msecs (HTTP/1.1 200) 4 headers in 225 bytes (1 switches on core 0)
[pid: 7550|app: 0|req: 5/17] 113.71.219.39 () {44 vars in 875 bytes} [Mon Jul 31 21:33:45 2017] GET /login/ => generated 9136 bytes in 40 msecs (HTTP/1.1 200) 4 headers in 256 bytes (1 switches on core 0)
[pid: 7546|app: 0|req: 3/18] 113.71.219.39 () {42 vars in 785 bytes} [Mon Jul 31 21:33:45 2017] GET /static/css/home.css => generated 82 bytes in 10 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7548|app: 0|req: 3/19] 113.71.219.39 () {42 vars in 768 bytes} [Mon Jul 31 21:33:45 2017] GET /static/js/home.js => generated 82 bytes in 9 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Mon Jul 31 21:33:45 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7536|app: 0|req: 1/20] 113.71.219.39 () {42 vars in 809 bytes} [Mon Jul 31 21:33:45 2017] GET /static/images/logo.png => generated 82 bytes in 446 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7550|app: 0|req: 6/21] 113.71.219.39 () {50 vars in 1027 bytes} [Mon Jul 31 21:33:45 2017] POST /get_gee_captcha/?t=1501507843877 => generated 105 bytes in 417 msecs (HTTP/1.1 200) 4 headers in 225 bytes (1 switches on core 1)
[pid: 7546|app: 0|req: 4/22] 113.71.219.39 () {52 vars in 1057 bytes} [Mon Jul 31 21:34:10 2017] POST /login/ => generated 0 bytes in 726 msecs (HTTP/1.1 302) 6 headers in 408 bytes (1 switches on core 1)
[pid: 7548|app: 0|req: 4/23] 113.71.219.39 () {46 vars in 901 bytes} [Mon Jul 31 21:34:10 2017] GET /user/ => generated 13362 bytes in 205 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 1)
[pid: 7550|app: 0|req: 7/24] 113.71.219.39 () {42 vars in 784 bytes} [Mon Jul 31 21:34:11 2017] GET /static/css/user.css => generated 82 bytes in 12 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
Mon Jul 31 21:34:11 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
[pid: 7550|app: 0|req: 8/25] 113.71.219.39 () {42 vars in 808 bytes} [Mon Jul 31 21:34:11 2017] GET /static/images/logo.png => generated 82 bytes in 10 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7546|app: 0|req: 5/26] 113.71.219.39 () {42 vars in 819 bytes} [Mon Jul 31 21:34:11 2017] GET /static/images/avatars/avatar1.png => generated 82 bytes in 11 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7533|app: 0|req: 1/27] 113.71.219.39 () {42 vars in 767 bytes} [Mon Jul 31 21:34:11 2017] GET /static/js/user.js => generated 82 bytes in 445 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7550|app: 0|req: 9/28] 113.71.219.39 () {48 vars in 923 bytes} [Mon Jul 31 21:36:10 2017] GET /user/ => generated 13362 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 7550|app: 0|req: 10/29] 113.71.219.39 () {46 vars in 837 bytes} [Mon Jul 31 21:36:10 2017] GET /static/css/user.css => generated 82 bytes in 9 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7548|app: 0|req: 5/30] 113.71.219.39 () {46 vars in 820 bytes} [Mon Jul 31 21:36:10 2017] GET /static/js/user.js => generated 82 bytes in 9 msecs (HTTP/1.1 404) 2 headers in 80 bytes (2 switches on core 0)
[pid: 7537|app: 0|req: 5/31] 113.71.219.39 () {46 vars in 861 bytes} [Mon Jul 31 21:36:10 2017] GET /static/images/logo.png => generated 82 bytes in 12 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)
[pid: 7537|app: 0|req: 5/32] 113.71.219.39 () {46 vars in 872 bytes} [Mon Jul 31 21:36:10 2017] GET /static/images/avatars/avatar1.png => generated 82 bytes in 14 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 0)
[pid: 7537|app: 0|req: 6/33] 113.71.219.39 () {46 vars in 864 bytes} [Mon Jul 31 21:36:11 2017] GET /static/images/favicon.ico => generated 82 bytes in 11 msecs (HTTP/1.1 404) 2 headers in 80 bytes (1 switches on core 1)

**Comment by Asheblog** [comment]
作者大神还望指点这个项目的网页指向是在哪个配置文件？

**Comment by lijianxiong** [comment]
楼主s哈哈哈。

**Comment by Asheblog** [comment]
location那里我写错目录了，可以关闭了
